"""
Generate a synthetic 8760-hour electricity price (LMP) profile for example 40 and
write it to ``electricity_price_profile.yaml`` (a bare YAML list of USD/kWh values).

The same file is ``!include``-d by both the electricity feedstock (to charge the
electric boiler) and the cost-merit dispatcher (to decide the hourly merit order),
so there is a single source of truth for the price signal.

Shape: cheap overnight, an evening peak, and a summer (cooling-load) seasonal rise.
Re-run to regenerate:  python make_electricity_price.py
"""

from pathlib import Path

import numpy as np


N = 8760
BASE = 0.04            # USD/kWh mean level
DIURNAL_AMP = 0.70     # fraction of base, evening peak / overnight trough
SEASONAL_AMP = 0.25    # fraction of base, summer peak
NOISE_STD = 0.03       # fractional multiplicative noise
FLOOR = 0.008          # USD/kWh floor


def main():
    t = np.arange(N)
    hour = t % 24
    day = t // 24
    diurnal = DIURNAL_AMP * np.cos(2.0 * np.pi * (hour - 18) / 24.0)   # max ~18:00, min ~06:00
    seasonal = SEASONAL_AMP * np.cos(2.0 * np.pi * (day - 200) / 365.0)  # max ~mid-July
    rng = np.random.default_rng(7)
    noise = rng.normal(0.0, NOISE_STD, N)
    price = np.maximum(FLOOR, BASE * (1.0 + diurnal + seasonal + noise))

    out = Path(__file__).parent / "electricity_price_profile.yaml"
    with out.open("w") as f:
        f.write("# Synthetic hourly electricity price [USD/kWh], 8760 values.\n")
        f.write("# Generated by make_electricity_price.py; !include-d as a bare list.\n")
        for v in price:
            f.write(f"- {v:.5f}\n")
    print(f"wrote {out} : n={len(price)} mean={price.mean():.4f} "
          f"min={price.min():.4f} max={price.max():.4f}")


if __name__ == "__main__":
    main()
